---
name: Zou CI

on: [push, pull_request]

jobs:
  ci:
    name: Test with different versions of Python 🐍
    runs-on: ubuntu-latest
    env:
      INDEXER_KEY: testkey0123456789
      PGPASSWORD: mysecretpassword
    strategy:
      fail-fast: false
      matrix:
        version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    services:
      postgres:
        image: "postgres:12.16"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt install -y ffmpeg
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
          cache: pip
      - name: Upgrade pip 📦
        run: >-
          pip install --upgrade pip setuptools
      - name: Install packages 📦
        run: >-
          pip install -r requirements.txt
      - name: Create database 🗄
        run: >-
          psql -c 'create database zoudb;' -U postgres -h 127.0.0.1
      - name: Launch docker for meilisearch 🐳
        run: |
          docker pull getmeili/meilisearch:v1.1
          docker run -it --rm -d -p 7700:7700 -e MEILI_MASTER_KEY=$INDEXER_KEY getmeili/meilisearch:v1.1
      - name: Run tests 🧪
        run: >-
          py.test
        env:
          DEBUG: 1
          MAIL_DEBUG_BODY: 1
          MAIL_ENABLED: False
